version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iiroegrouegro;ihe43j3@]
      POSTGRES_DB: test
    networks:
      - vol.13
networks:
  freecodecampss:
